### ISSUE TITLE
v0.2.0 checklist

### ISSUE THREAD

**Issue by merlinoa** [merlinoa/shinyFeedback#22]
- [x] add support for pickerInput #10
- [ ] add support for fileInput #9 
- [ ] supply our own css classes and use these classes rather than using the bootstrap 3 classes
- [ ] document the process of adding support for new inputs
- [x] remove the snackbar
- [ ] create issue and fix icon position when input label == `NULL`
